language: minimal

services:
  - docker

install:
  - docker-compose -f docker-compose.yml build

script:
  # Run Javascript tests
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run assets
  # Run Python tests
  - cp server/instance/config.py.sample server/instance/config.py
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run -u root server

after_success:
  # Upload coverage reports in ./coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)